<a href="https://colab.research.google.com/github/SaurabhChakravorty/SHALA2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [0]:
import numpy as np
#Generating random integers with random numbers
a = np.random.rand(3,5)
b = np.random.rand(3,5)
#print(a)
#print(b)

[[0.96394178 0.27920621 0.42566116 0.13467653 0.51332673]
 [0.53192613 0.25730489 0.96899965 0.26667661 0.88865997]
 [0.90014131 0.80647801 0.13067992 0.30368118 0.47531048]]
[[0.61751679 0.75402334 0.7731646  0.42218347 0.82435659]
 [0.7075403  0.27177099 0.20963345 0.01557946 0.8955613 ]
 [0.00620559 0.98023297 0.54428153 0.09687846 0.07500894]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all positive integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [5]:
c = [i for i in range(100)]
d = np.zeros((3, 3))
#print(c,d)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [6]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [0]:
f = np.zeros((5,5))
g = np.identity(5)
#print(f)
#print(g)

Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $d^\prime$ and print **YES** when the shapes of $d$ and $d^\prime$ are same. Otherwise print **NO**.

In [21]:
#Reshaping array into 10 * 10
h = np.reshape(c, (10,10)).T
d' = 

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [0]:
A = np.random.rand(2,10,5)



You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [0]:
np.random.seed(0)
X = np.random.rand(10,5)



Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)




## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.